// apps/angular-monorepo-todo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { sumTwoNumbers } from '@angular-monorepo-todo/utils';
@Component({
  selector: 'angular-monorepo-todo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'angular-monorepo-todo';
  num1 = 2;
  num2 = 3;
  ngOnInit(): void {
    console.log(sumTwoNumbers(this.num1, this.num2))
  }
}

<div class="angular-app-wrapper">
    Angular App
    <a href="http://localhost:4201">Move to react app</a>
</div>
<router-outlet></router-outlet>

// apps/react-monorepo-shop/src/app/app.tsx
import { sumTwoNumbers } from '@angular-monorepo-todo/utils';

export function App() {
  console.log(sumTwoNumbers(4, 5))
  return (
    <div className='react-app-wrapper'>
      <div className='header'>React App</div>
      <a href="http://localhost:4200">move to angular app</a>
    </div>
  );
}

export default App;
